name: tox
on: [push, pull_request]
jobs:
  tox:
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        python: [3.6, 3.7, 3.8, 3.9]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - run: pip install tox
      - if: matrix.python == '3.6'
        run: TOXENV=py36 tox
      - if: matrix.python == '3.7'
        run: TOXENV=py37 tox
      - if: matrix.python == '3.8'
        run: TOXENV=py38 tox
      - if: matrix.python == '3.9'
        run: TOXENV=py39 tox
